### PR TITLE
update format with rubocop --safe-auto-correct

### PR DESCRIPTION
**Pull request by fniscak**
I hope that this time the update is correct.

### CODE REVIEW

**Comment by jhund** [comment]
@fniscak looks great. There is one more thing I'd like you to change: The in-page links on the scope patterns page need some updating. Until now the TOC at the top of the page referred to <a> tags I inserted manually. Now the hrefs in the TOC are changed to go to the auto-generated ids on the headings (hyphens vs. underscores). This is fine, however now we don't need the manual <a> tags any more. Could you please remove them?

**Comment by fniscak** [comment]
links/anchors have been corrected - vscode plugin effects

**Comment by jhund** [comment]
@fniscak thank you for the PR!

**Comment by fniscak** [comment]
I felt that it needed to be done. It is just a first step.

**Pull request merged**
