### PR TITLE
Fix 'permit' params to allow multiple form inputs for a single scope

### LINKED ISSUE #114: Filterrific Not Passing Multiple Parameters to Scope
I have a filterrific scope that accepts multiple parameters. The scope appears to be functioning correctly (I can call Marketplace::Lot.with_price({}) in the console and it returns the correct results), but filterrific isn't passing any data to it when I enter information on the form.

Here is my filterrific declaration in the model

```ruby
  filterrific(
    default_filter_params: { sorted_by: 'time_remaining_asc' },
    available_filters: [
      :with_price,
      :sorted_by,
      :lots_with_item_type,
      :search_query
    ]
  )
```

Here is what my controller looks like:

```ruby
@filterrific = initialize_filterrific(
  Marketplace::Lot,
  params[:filterrific],
  select_options: {
    sorted_by: Marketplace::Lot.options_for_sorted_by,
    item_types: Marketplace::Lot.options_for_item_types
  },
  persistence_id: 'marketplace_key',
) or return

@lots = @filterrific.find.paginate(page: params[:page], per_page: 20)
```

and my view

```
    <%= f.fields_for :with_price,  OpenStruct.new(@filterrific.with_price) do |with_price_fields| %>
    <div class="marketseach__shards shards">
      <%= with_price_fields.text_field :shards_min, class: 'marketplace__value input', placeholder: 'Low Value' %>
      -
      <%= with_price_fields.text_field :shards_max, class: 'marketplace__value input', placeholder: 'High Value' %>
    </div>
    <span class="marketsearch__text">or</span>
    <div class="marketsearch__gems gems">
      <%= with_price_fields.text_field :gems_min, class: 'marketplace__value input', placeholder: 'Low Value' %>
      -
      <%= with_price_fields.text_field :gems_max, class: 'marketplace__value input', placeholder: 'High Value' %>
    </div>
    <% end %>

```
When I submit the form, the price fields appear in the params hash

```
"filterrific"=>
 { "search_query"=>"Programming",
   "lots_with_item_type"=>"",
   "with_price"=>{"shards_min"=>"200", "shards_max"=>"", "gems_min"=>"", "gems_max"=>""},
   "sorted_by"=>"alpha_asc"
 },

```
However, it never gets to the scope (I have a binding.pry in the scope that never gets hit). I should note that all other scopes are working correctly.

I'm sure I'm missing something obvious but I can't find it for the life of me.

### PR DESCRIPTION
**Pull request by ayaman**
Resolves #114

### CODE REVIEW

**Comment by edwardmp** [comment]
Thanks for this, but in my case it doesn't solve the problem yet. It still complains about a unpermitted parameter.. will investigate further

**Comment by edwardmp** [comment]
Got it. The comparison `is_a? Hash` returns false in my case, because `p` is not a `Hash` but an instance of `ActionController::Parameters` (not sure why this actually differs with your situation).

Therefore I propose the following change:
`permissible_filter_params << ([ActionController::Parameters, Hash].member?(filterrific_params[p].class) ? { p => filterrific_params[p].keys } : p)`

Alternatively, instead of comparing with a fixed list of classes, we could also just check if the instance responds to they `keys` method.

For now I'll submit a pull request to your pull request containing the former fix.

**Comment by edwardmp** [comment]
I know why it worked in your case. You must have tested on Rails 4 or earlier. Back then `ActionController::Parameters` inherited from hash, so the comparison to a hash evaluated to true. But starting in Rails 5 this is no longer the case and `ActionController::Parameters` inherit from `Object` instead.

Thus, what was actually passed will always be of type `ActionController::Parameters` therefore I propose to just only check that the type conforms to that, rather than checking against the Hash type. I'll modify the pull request to account for this.

More info: http://blog.bigbinary.com/2016/07/25/parameters-no-longer-inherit-from-hash-with-indifferent-access-in-rails-5.html

**Comment by ayaman** [comment]
That makes sense, thank you for the update! I merged your pull request and it seems everything is working fine.

**Comment by blaedj** [comment]
This also fixes #113 now.

**Comment by patrickworkit** [comment]
Thanks for fixing this! It would be great to have this merged in.

**Comment by edwardmp** [comment]
@jhund Could you please merge this in, as various important fixes by various contributors are included in this PR, thanks 👍

**Comment by jhund** [comment]
Thank you for the fix!

**Pull request merged**
